version: '2.2'

services:
  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    expose:
        - 9000
    volumes:
        - ./src:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=wordpress
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=wordpress
    depends_on:
        - mysql
    restart: always

  nginx:
    image: nginx:latest
    ports:
        - '80:80'
    volumes:
        - ./nginx:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx
        - ./src:/var/www/html
    depends_on:
        - wordpress
    restart: always

  mysql:
    image: mysql:5.5
    expose:
        - 3306
    volumes:
        - ./.data/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=wordpress
    restart: always
